import {createRouter, createWebHistory} from 'vue-router';

const routes=[
    {
        path: '/',
        name: '',
        children:[
            {
               path:'',
               name:'',
               component:()=>import('@/components/root_page.vue'),//主页
               children:[
                {
                    path:'/',
                    name:'illustration',
                    component:()=>import('@/components/Illustration_page/Illustration_page.vue'),//插画
                },
                {
                    path:'/comic',
                    name:'comic',
                    component:()=>import('@/components/cartoon/cartoon_page.vue')//漫画
                },
                {
                    path:'/novel',
                    name:'novel',
                    component:()=>import('@/components/novel_page/novel_page.vue')//小说
                },
                {
                    path:'/ill_content',
                    name:'ill_content',
                    component:()=>import('@/components/content_page/ill_page/ill_index.vue')//插画内容
                },
                {
                    path:'/comic_content',
                    name:'comic_content',
                    component:()=>import('@/components/content_page/comic_page/comic_index.vue')//漫画内容
                },
                {
                    path:'/novel_content',
                    name:'novel_content',
                    component:()=>import('@/components/content_page/novel_page/novel_index.vue')//小说内容
                },
                {
                    path:'/self_user_center',
                    name:'self_user_center',
                    component:()=>import('@/components/user_center_page/user_center_page.vue')//个人中心
                },
                {
                    path:'/comic_content',
                    name:'comic_content',
                    component:()=>import('@/components/content_page/comic_page/comic_index.vue')//漫画内容
                },{
                    path:'/novel_content',
                    name:'novel_content',
                    component:()=>import('@/components/content_page/novel_page/novel_index.vue')//小说内容
                },{
                    path:'/other_user_center',
                    name:'other_user_center',
                    component:()=>import('@/components/other_user_center_page/user_center_page.vue')//他人个人中心
                },
                {
                    path:'/chat',
                    name:'chat',
                    component:()=>import('@/components/chat_page/chat_box.vue')//聊天
                },
                {
                    path:'/upload_ill',
                    name:'upload_ill',
                    component:()=>import('@/components/headpage_file/file/contribute/ill/ill_page.vue')//上传插画
                },
                {
                    path:'/upload_comic',
                    name:'upload_comic',
                    component:()=>import('@/components/headpage_file/file/contribute/comic/comic_page.vue')//上传漫画
                },
                {
                    path:'/upload_novel',
                    name:'upload_novel',
                    component:()=>import('@/components/headpage_file/file/contribute/novel/novel_page.vue')//上传小说
                },
                {
                    path:'/upload_status',
                    name:'upload_status',
                    component:()=>import('@/assets/model/work_contribute_review/components/root.vue')//上传状态
                },
                {
                    path:'/com_an_article',
                    name:'com_an_article',
                    component:()=>import('@/components/commission_an_article/com_an_article.vue')//委托创作,约稿
                },
                {
                    path:'/his_page',
                    name:'his_page',
                    component:()=>import('@/components/browse_history_page/br_his_index_page.vue')//浏览历史
                },
                {
                    path:'/data_analysis',
                    name:'data_analysis',
                    component:()=>import('@assets/model/data_analysis/components/root.vue')//数据分析
                },
                {
                    path:'/vip_welcome',
                    name:'vip_welcome',
                    component:()=>import('@/components/vip/vip_welcome.vue'),//VIP欢迎页,
                    meta: {
                        title: '会员支付 - 插画星球'
                      }
                },
                {
                    path:'/vip_pay',
                    name:'vip_pay',
                    component:()=>import('@/components/vip/pay.vue'),//会员支付,
                    meta: {
                        title: '会员支付 - 插画星球'
                      }
                },
                {
                    path:'/wallet',
                    name:'wallet',
                    component:()=>import('@/components/wallet/wallet_index.vue'),//钱包,
                    meta: {
                        title: '钱包 - 插画星球'
                      }
                },
                {
                    path:'/init_pay_account',
                    name:'init_pay_account',
                    component:()=>import('@/components/wallet/init_pat_account.vue'),//初始化支付账户,
                },
                {
                    path:'/create_func',
                    name:'create_func',
                    component:()=>import('@/components/commission_an_article/sub_page/create_func.vue'),//创建约稿方案
                }
               ] 
            }
        ]
    },
    {
        path:'/login',
        name:'login',
        component:()=>import('@/components/login/login_page.vue')//登录
    },
    {
        path:'/register',
        name:'register',
        component:()=>import('@/components/register/register_page.vue')//注册
    },
    {
        path:'/reset_password',
        name:'reset_password',
        component:()=>import('@assets/model/reset_password/reset_password.vue')//重置密码
    }
]
const router = createRouter({
    history: createWebHistory(),
    routes
})

export {router};