import {createRouter, createWebHistory} from 'vue-router'

const routes=[
    {
        path:'/',
        name:'index',
        children:[
            {
                path:'/',
                name:'',
                component:()=>import('@/components/index.vue'),
                children:[
                    {
                        path:'/',
                        name:'',
                        component:()=>import('@/components/content.vue'),
                        children:[
                            {
                                path:'/',
                                name:'user',
                                component:()=>import('@/components/model/user_control.vue')
                            },
                            {
                                path:'/ill',
                                name:'ill',
                                component:()=>import('@/components/model/ill_control.vue')
                            },
                            {
                                path:'/comic',
                                name:'comic',
                                component:()=>import('@/components/model/comic_control.vue')
                            },
                            {
                                path:'/novel',
                                name:'novel',
                                component:()=>import('@/components/model/novel_control.vue')
                            },{
                                path:'/comment',
                                name:'comment',
                                component:()=>import('@/components/model/commection_control.vue')
                            },{
                                path:'/generate_password_card',
                                name:'generate_password_card',
                                component:()=>import('@/components/model/generate_password_card.vue')
                            },{
                                path:'/send_notice',
                                name:'send_notice',
                                component:()=>import('@/components/model/send_notice.vue')
                            },{
                                path:'/send_msg',
                                name:'send_msg',
                                component:()=>import('@/components/model/send_msg/send.vue')//向目标用户发送消息
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        path:'/login',
        name:'login',
        component:()=>import('@/components/model/login_page.vue')
    }
]
const router=createRouter({
    history:createWebHistory(),
    routes
})
export {router}