cover_dict = {
    'template_1': {
        'path': 'H:/web_project/image/novel/cover_material/template_1.jpg',
        'text': '标题示例',
        'x': [150, 500],
        'y': [150, 750],
        'font-size': 28,
        'font-color': '#dfae76',
        'direction': 'vertical',
        'align': 'vertical-center',
        'font': 'H:/web_project/font/AaDongQiChangYueYangLouJi-2.ttf'
    },
    'template_2': {
        'path': 'H:/web_project/image/novel/cover_material/template_2.jpg',
        'text': '标题示例',
        'x': [50, 600],
        'y': [200, 400],
        'font-size': 28,
        'font-color': ['#85bbf7', '#587cd0'],
        'gradient-direction': ['left', 'right'],
        'gradient-model': 'line-random',
        'direction': 'transverse',
        'align': 'transverse-center',
        'font': 'H:/web_project/font/AaMaoZhuaShaoNv-2.ttf'
    },
    'template_3': {
        'path': 'H:/web_project/image/novel/cover_material/template_3.jpg',
        'text': '标题示例',
        'x': [425, 580],
        'y': [300, 800],
        'font-size': 28,
        'font-color': ['#8ce1fe', '#feb4b3'],
        'gradient-direction': ['top', 'bottom'],
        'gradient-model': 'line',
        'direction': 'vertical',
        'align': 'vertical-center',
        'font': 'H:/web_project/font/AaZhuNiWoMingMeiXiangChunTian-2.ttf'
    },
    'template_4': {
        'path': 'H:/web_project/image/novel/cover_material/template_4.jpg',
        'text': '标题示例',
        'x': [100, 500],
        'y': [100, 750],
        'font-size': 28,
        'font-color': ['#45b5e5', '#ff82b1'],
        'gradient-direction': ['top-left-corner', 'bottom-right-corner'],
        'gradient-model': 'line',
        'direction': 'transverse',
        'align': 'transverse-center',
        'font': 'H:/web_project/font/XiangJiaoXiaoXingYunLingGanTi-2.ttf'
    },
    'template_5': {
        'path': 'H:/web_project/image/novel/cover_material/template_5.jpg',
        'text': '标题示例',
        'x': [235, 400],
        'y': [125, 750],
        'font-size': 26,
        'font-color': ['#868686', '#212121'],
        'gradient-direction': ['top', 'bottom'],
        'gradient-model': 'line',
        'direction': 'vertical',
        'align': 'vertical-center',
        'font': 'H:/web_project/font/yibiyihuachaoheiti-2.ttf'
    },
    'template_6': {
        'path': 'H:/web_project/image/novel/cover_material/template_6.jpg',
        'text': '标题示例',
        'x': [125, 550],
        'y': [125, 675],
        'direction': 'transverse',
        'font-size': 28,
        'font-color': ['#714b1c', '#f7c852'],
        'gradient-direction': ['left', 'right'],
        'gradient-model': 'line',
        'align': 'transverse-center',
        'font': 'H:/web_project/font/ZiHunJianQiShouShu(ShangYongXuShouQuan)-2.ttf'
    },
    'template_7': {
        'path': 'H:/web_project/image/novel/cover_material/template_7.jpg',
        'text': '标题示例',
        'x': [50, 575],
        'y': [250, 625],
        'font-size': 28,
        'font-color': ['#ff9da2', '#fd956e'],
        'gradient-direction': ['left', 'right'],
        'gradient-model': 'line-random',
        'direction': 'transverse',
        'align': 'transverse-center',
        'font': 'H:/web_project/font/AaDongQiChangYueYangLouJi-2.ttf'
    },
    'temp_path': 'H:/web_project/image/novel/temp_cover',
}